name: Coverage

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

concurrency:
  group: coverage
  cancel-in-progress: false

jobs:
  upload:
    name: Upload Test Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: hoverkraft-tech/compose-action@v2.1.0
        with:
          compose-file: ./.github/workflows/docker-compose.yml
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: '22.11.0'
          cache: pnpm
      - run: pnpm install
      - run: pnpm run coverage
      - uses: coverallsapp/github-action@v2
