services:
  kysely_codegen_libsql:
    container_name: kysely_codegen_libsql
    image: ghcr.io/libsql/sqld:latest
    network_mode: host
    restart: always

  kysely_codegen_mysql:
    container_name: kysely_codegen_mysql
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
    image: mysql:latest
    network_mode: host
    restart: always

  kysely_codegen_postgres:
    container_name: kysely_codegen_postgres
    environment:
      - POSTGRES_DB=database
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
    image: postgres:latest
    network_mode: host
    restart: always
